# Generated by Django 3.1.7 on 2021-04-04 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('being_contacted', models.BooleanField(default=False)),
                ('contact_start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('phone_num', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
                ('being_contacted', models.BooleanField(default=False)),
                ('contact_start', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.people')),
            ],
        ),
        migrations.CreateModel(
            name='TestContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contacted', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.test')),
            ],
        ),
        migrations.CreateModel(
            name='ContactContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contacted', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='case_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.people'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='shared.addresses'),
        ),
        migrations.AddField(
            model_name='contact',
            name='positive_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.test'),
        ),
    ]
