# Generated by Django 3.1.7 on 2021-02-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=8)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=3035)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('phone_num', models.CharField(max_length=13)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.people')),
            ],
        ),
        migrations.CreateModel(
            name='TestContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.test')),
            ],
        ),
        migrations.CreateModel(
            name='ContactContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='case_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.people'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.addresses'),
        ),
        migrations.AddField(
            model_name='contact',
            name='positive_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.test'),
        ),
    ]
