# Generated by Django 3.1.7 on 2021-03-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='people',
            name='lname',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='shared.addresses'),
        ),
    ]
