# Generated by Django 3.1.7 on 2021-03-03 17:32

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20210303_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
