# Generated by Django 3.1.7 on 2021-03-16 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontacted',
            name='date_contacted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(default='flooble@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcontacted',
            name='date_contacted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.BooleanField(),
        ),
    ]
