# Generated by Django 3.1.7 on 2021-05-10 16:51

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035)),
                ('population', models.IntegerField()),
                ('type', models.CharField(choices=[('CTRY', 'Country'), ('REG', 'Region'), ('CNTY', 'County/Unitary Authority'), ('LA', 'Local Authority District')], default='LA', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.UUIDField(primary_key=True, serialize=False)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('cluster_size', models.IntegerField(default=0)),
                ('indices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
