# Generated by Django 3.1.7 on 2021-04-04 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='points_in_cluster',
            new_name='cluster_size',
        ),
        migrations.AddField(
            model_name='cluster',
            name='indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
