# Generated by Django 3.1.7 on 2021-04-05 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20210404_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
