# Generated by Django 3.1.7 on 2021-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_auto_20210405_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
