
name: Auto-Test

# Automatically runs tests every time main branch is changed
on: push

jobs:
  auto-test:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        uses: github

